#!/bin/bash

# This script is a dirty hack to fix the edit-URLs in the html-files
# generated by mdbook.
#
echo "Fixing URLs..."
for file in book/*.html book/*/*.html
do
  sed -i -e 's#master/out#master/src#g' $file
done
